import { IIsoStore, WaveMode } from './iso.types';

export const initialState: IIsoStore = {
  isoState: {
    cameraId: '',
    meshId: '',
    groupId: '',
    dotId: '',
    layerId: '',
    shotId: '',
    focusedShotId: '',
    paramsId: '',
    isAudioReady: false,
    isBoardReady: false,
    isDataReady: false,
    isSceneReady: false,
    isSyncOn: false,
    musicUrl: 'https://ai-boards-d2ecd.web.app/sound/modelZ.mp3',
    isMusicReady: false,
    voiceUrl: 'https://ai-boards-d2ecd.web.app/sound/modelZ-voice.mp3',
    isVoiceReady: false,
    waveMode: WaveMode.Full,
    isPerspectiveOn: false,
    isGizmoOn: false,
    isVolumeOn: true,
    isBezierOn: false,
    isCenterBallOn: false,
    isArc: false,
    lastMoveTimestamp: Date.now(),
    isDimmerOn: false,
    range: [0, 1],
    isRangeActive: true,
    isSetPieceOn: true,
    totalDuration: 0,
    timelineWidth: 0,
  },
  sceneItems: {
    sound: {
      id: 'sound',
      itemType: 'sfx',
      params: {
        url: 'https://github.com/dht/boards-starter/raw/main/scenes/s1.png',
      },
    },
  },
  layers: {
    dots: {
      id: 'dots',
      order: 1,
      isActive: true,
    },
    viz: {
      id: 'viz',
      order: 2,
      isActive: true,
    },
    sky: {
      id: 'sky',
      order: 3,
      isActive: true,
    },
    hud: {
      id: 'hud',
      order: 4,
      isActive: true,
    },
    sfx: {
      id: 'sfx',
      order: 5,
      isActive: true,
    },
    vfx: {
      id: 'vfx',
      order: 6,
      isActive: true,
    },
    txt: {
      id: 'txt',
      order: 7,
      isActive: true,
    },
    vce: {
      id: 'vce',
      order: 8,
      isActive: true,
    },
    ani: {
      id: 'ani',
      order: 9,
      isActive: true,
    },
  },
  playState: {
    startTime: 0,
    currentTime: 0,
    playbackSpeed: 1,
    playbackStatus: 'idle',
  },
  groups: {
    car: {
      id: 'car',
      itemIds: [
        'Object_2',
        'Object_3',
        'Object_4',
        'Object_5',
        'Object_6',
        'Object_7',
        'Object_8',
        'Object_9',
        'Object_10',
        'Object_11',
        'Object_12',
        'Object_13',
      ],
      itemType: 'group',
      params: {
        position: { x: 0, y: 0, z: 0 },
      },
    },
  },
  control: {
    formType: 'mesh',
    isDot: false,
    isSetPiece: false,
    pos: {
      x: -40,
      y: 0,
      z: -40,
      b1: 0.5,
      b2: 0.5,
      b3: 0.5,
      b4: 0.5,
      isAnimated: true,
      l: 1,
    },
  },
  dots: {
    g1: {
      id: 'g1',
      itemId: 'g1',
      timestamp: 10,
      layerId: 'dots',
      dotType: 'mesh',
      params: {
        x: -40,
        y: 0,
        z: -40,
        b1: 0.5,
        b2: 0.5,
        b3: 0.5,
        b4: 0.5,
        isAnimated: true,
        l: 1,
      },
      isSelected: false,
    },
    v1: {
      id: 'v1',
      itemId: 'g1',
      layerId: 'viz',
      dotType: 'viz',
      timestamp: 0,
      params: {
        show: true,
      },
    },
    sfx1: {
      id: 'sfx1',
      layerId: 'sfx',
      dotType: 'sfx',
      itemId: '',
      timestamp: 19800,
      params: {
        url: 'http://localhost:3001/sounds/modelz/flyby.mp3',
        volume: 0,
      },
    },
    vfx1: {
      id: 'vfx1',
      layerId: 'vfx',
      dotType: 'vfx',
      itemId: '',
      timestamp: 19800,
      params: {
        url: 'http://localhost:3001/sounds/modelz/flyby.mp3',
        volume: 0,
      },
    },
    sky1: {
      id: 'sky1',
      layerId: 'sky',
      dotType: 'sky',
      itemId: '',
      timestamp: 10,
      params: {
        url: 'http://localhost:3001/scenes/s2.png',
      },
    },
    h1: {
      id: 'h1',
      timestamp: 0,
      dotType: 'hud',
      itemId: '',
      layerId: 'hud',
      params: {
        hudId: 'h1',
      },
    },
  },
  shots: {
    s1: {
      id: 's1',
      name: '',
      duration: 0,
      timestamp: 0,
    },
  },
};
